version: '2.2'

services:

  app:
    ports:
      - 8765:80
    env_file:
      - prod.env
    cpus: 1
    mem_limit: 512m
    restart: always

  mysql:
    volumes:
      - ./local/mysql:/var/lib/mysql
    env_file:
      - prod.env
    cpus: 1
    mem_limit: 1g
    restart: always

  drush:
    env_file:
      - prod.env
    cpus: 1
    mem_limit: 512m

