version: '2.2'

services:

  app:
    image: drupal:7.57-apache
    volumes:
      - ./www/sites:/var/www/html/sites
      - /var/www/html
    links:
      - mysql

  mysql:
    image: mysql:5

  drush:
    image: drush/drush:7
    volumes_from:
      - app
    working_dir: /var/www/html
    links:
      - mysql
