version: '2.2'

services:

  app:
    image: nginx 
    environment:
      - NGINX_PORT=80
    links:
      - php
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - php:ro

  php:
    image: drupal:7.56-fpm
    volumes:
      - ./www/sites:/var/www/html/sites
      - /var/www/html
    links:
      - mysql

  mysql:
    image: mysql:5

  drush:
    image: drush/drush:7
    volumes_from:
      - php
    working_dir: /var/www/html
    links:
      - mysql
