version: '2.2'

services:

  drupal:
    image: drupal:7.56-apache
    ports:
      - 8080:80
    volumes:
      - ./www/sites:/var/www/html/sites
      - /var/www/html
    links:
      - mysql
    env_file:
      - shared.env
  mysql:
    image: mysql:5
    env_file:
      - shared.env

  drush:
    image: drush/drush:7
    volumes_from:
      - drupal
    working_dir: /var/www/html
    links:
      - mysql
    env_file:
      - shared.env
